on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        redis-version: ["6.x", "7.x"]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: gofmt
      run: test -z "`gofmt -l .`"
    - name: golint
      run: test -z "`golint ./...`"
    - name: go test
      run: go test -v ./...
    - name: Run Redis Realtime Example
      run: cd redis/realtime/example && go build -o realtime && ./realtime